# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

try:
    from phantom_protocol_schemas import task_pb2 as task__pb2
except ImportError:
    import task_pb2 as task__pb2  # type: ignore[no-redef]

GRPC_GENERATED_VERSION = "1.78.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in task_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaskDistributionStub(object):
    """gRPC service implemented by workers, called by the controller"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
            "/phantom.protocol.TaskDistribution/SubmitTask",
            request_serializer=task__pb2.TaskRequest.SerializeToString,
            response_deserializer=task__pb2.TaskResult.FromString,
            _registered_method=True,
        )


class TaskDistributionServicer(object):
    """gRPC service implemented by workers, called by the controller"""

    def SubmitTask(self, request, context):
        """Submit a task and receive the result synchronously (unary RPC)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaskDistributionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SubmitTask": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitTask,
            request_deserializer=task__pb2.TaskRequest.FromString,
            response_serializer=task__pb2.TaskResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "phantom.protocol.TaskDistribution", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "phantom.protocol.TaskDistribution", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class TaskDistribution(object):
    """gRPC service implemented by workers, called by the controller"""

    @staticmethod
    def SubmitTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/phantom.protocol.TaskDistribution/SubmitTask",
            task__pb2.TaskRequest.SerializeToString,
            task__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
