# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "task.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


try:
    from phantom_protocol_schemas import common_pb2 as common__pb2
except ImportError:
    import common_pb2 as common__pb2  # type: ignore[no-redef]


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ntask.proto\x12\x10phantom.protocol\x1a\x0c\x63ommon.proto"\xd7\x01\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x41\n\nparameters\x18\x03 \x03(\x0b\x32-.phantom.protocol.TaskRequest.ParametersEntry\x12\x16\n\x0eschema_version\x18\x04 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xf4\x01\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x38\n\x06result\x18\x03 \x03(\x0b\x32(.phantom.protocol.TaskResult.ResultEntry\x12,\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1d.phantom.protocol.ErrorStatus\x12\x16\n\x0eschema_version\x18\x05 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32]\n\x10TaskDistribution\x12I\n\nSubmitTask\x12\x1d.phantom.protocol.TaskRequest\x1a\x1c.phantom.protocol.TaskResultb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "task_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TASKREQUEST_PARAMETERSENTRY"]._loaded_options = None
    _globals["_TASKREQUEST_PARAMETERSENTRY"]._serialized_options = b"8\001"
    _globals["_TASKRESULT_RESULTENTRY"]._loaded_options = None
    _globals["_TASKRESULT_RESULTENTRY"]._serialized_options = b"8\001"
    _globals["_TASKREQUEST"]._serialized_start = 47
    _globals["_TASKREQUEST"]._serialized_end = 262
    _globals["_TASKREQUEST_PARAMETERSENTRY"]._serialized_start = 213
    _globals["_TASKREQUEST_PARAMETERSENTRY"]._serialized_end = 262
    _globals["_TASKRESULT"]._serialized_start = 265
    _globals["_TASKRESULT"]._serialized_end = 509
    _globals["_TASKRESULT_RESULTENTRY"]._serialized_start = 464
    _globals["_TASKRESULT_RESULTENTRY"]._serialized_end = 509
    _globals["_TASKDISTRIBUTION"]._serialized_start = 511
    _globals["_TASKDISTRIBUTION"]._serialized_end = 604
# @@protoc_insertion_point(module_scope)
